# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow_user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.DeleteModel(
            name='GrammLetterRecipients',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
