# Generated by Django 3.1.5 on 2021-01-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammLetterRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
