# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0003_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Images_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
