# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0004_auto_20210117_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Images_image',
            field=models.ImageField(null=True, blank=True, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='gramm.Profile'),
            preserve_default=False,
        ),
    ]
