# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0005_auto_20210117_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
