# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0006_auto_20210117_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Images_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramm.Profile'),
        ),
    ]
