# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 14:10
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0007_auto_20210117_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
