# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0009_auto_20210117_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
